"""
Dossier Assembler

Assembles complete Commander-grade intelligence dossier from pipeline results.

Reuses components from generate_zo_intelligence_dossiers.py but with modular structure.
"""

from datetime import datetime
from typing import Dict, Any

def assemble(trial: Dict[str, Any], patient: Dict[str, Any]) -> str:
    """
    Assemble complete intelligence dossier.
    
    Args:
        trial: Trial dict with _filter_metadata from pipeline
        patient: Complete patient profile
    
    Returns:
        Markdown-formatted dossier
    """
    metadata = trial.get('_filter_metadata', {})
    nct_id = trial.get('nct_id', 'UNKNOWN')
    title = trial.get('title', 'N/A')
    
    # Extract pipeline results
    stage1 = metadata.get('stage1')
    stage2 = metadata.get('stage2')
    stage3 = metadata.get('stage3')
    stage4 = metadata.get('stage4')
    stage5 = metadata.get('stage5')
    
    composite_score = metadata.get('composite_score', 0.0)
    eligibility_prob = stage4.metadata.get('eligibility_probability', 0.0) if stage4 else 0.0
    
    # Determine tier
    if composite_score >= 0.8:
        tier = 'TOP_TIER'
    elif composite_score >= 0.6:
        tier = 'GOOD_TIER'
    else:
        tier = 'OK_TIER'
    
    # Build markdown
    md = f"""# ⚔️ TRIAL INTELLIGENCE REPORT: {nct_id} ⚔️

**Trial Name**: {title[:60]}...  
**Patient**: {patient['demographics']['name']} (ID: {patient['demographics']['patient_id']})  
**Generated**: {datetime.now().isoformat()}  
**Generated By**: Zo (Lead Commander)  
**Match Tier**: {tier}  
**Composite Score**: {composite_score:.2f}/1.00  
**Eligibility Probability**: ~{eligibility_prob*100:.0f}%

**ClinicalTrials.gov**: https://clinicaltrials.gov/study/{nct_id}

---

## 🔥 WHY THIS MATTERS - CRITICAL ANALYSIS

**Status**: {trial.get('status', 'UNKNOWN')}  
**Phase**: {trial.get('phase', 'N/A')}  
**Sponsor**: {trial.get('sponsor_name', 'Not specified')}

### ✅ PIPELINE ASSESSMENT:

"""
    
    # Add Stage 1 reasons
    if stage1:
        for reason in stage1.reasons:
            md += f"{reason}\n"
    
    # Add Stage 2 (trial type)
    if stage2:
        trial_type = stage2.metadata.get('trial_type', 'UNKNOWN')
        md += f"- ✅ {trial_type} treatment trial\n"
    
    # Add Stage 3 (locations)
    if stage3:
        matching_locs = stage3.metadata.get('matching_locations', stage3.metadata.get('nyc_locations', []))
        md += f"- ✅ {len(matching_locs)} location(s)\n"
    
    # Add Stage 4 (eligibility)
    if stage4:
        md += f"- ⚠️ Eligibility: ~{eligibility_prob*100:.0f}% (pending biomarkers)\n"
    
    md += f"""
**Semantic Similarity**: {trial.get('similarity_score', 0):.3f} (vector search match)

---

## 🧬 ELIGIBILITY ASSESSMENT

| Criterion | Patient's Status | Match | Action Required |
|-----------|-----------------|-------|-----------------|
| Stage IV epithelial ovarian | Stage {patient['disease']['figo_stage']} {patient['disease']['primary_diagnosis']} | ✅ PASS | None |
| BRCA wildtype | Germline {patient['biomarkers']['germline_status'].lower()} | ✅ PASS | None |
| HER2 Status | {patient['biomarkers']['her2_status']} | ⚠️ GATE | HER2 IHC (3-5 days) |
| HRD Status | {patient['biomarkers']['hrd_status']} | ⚠️ PENDING | MyChoice CDx (7-10 days) |
| Treatment Line | {patient['treatment']['line']} | ✅ PASS | None |
| Tissue Available | {patient['eligibility']['tissue_availability']['has_tissue']} | ✅ PASS | None |
| Performance Status | ECOG {patient['disease']['performance_status']} | ✅ PASS | None |
| Geographic Access | {patient['logistics']['location']} | ✅ PASS | None |

**Probability Patient Is Eligible**: ~{eligibility_prob*100:.0f}%  
"""
    
    # Add breakdown
    if stage4 and stage4.reasons:
        md += f"**Calculation**: {' × '.join(stage4.reasons)}\n"
    
    md += "\n---\n\n"
    
    # Add LLM analysis if available
    if stage5 and stage5.metadata.get('llm_analysis'):
        md += f"""## 🎯 WHY THIS TRIAL IS A GOOD FIT (LLM Analysis)

{stage5.metadata['llm_analysis']}

---

"""
    
    # Add decision tree
    md += _generate_decision_tree(trial, patient, eligibility_prob)
    
    # Add strategic implications
    md += _generate_strategic_scenarios(trial, patient, eligibility_prob)
    
    # Add full eligibility text
    md += f"""
## 📋 FULL ELIGIBILITY TEXT

### Eligibility Criteria
{trial.get('eligibility_text', 'Eligibility criteria not available.')}

---

## 📊 TRIAL DESCRIPTION

{trial.get('description_text', 'Description not available.')}

---

"""
    
    # Add location details
    md += _generate_location_section(trial, stage3)
    
    # Add critical gates
    md += _generate_critical_gates(trial, patient)
    
    # Add tactical recommendations
    md += _generate_tactical_recommendations(tier, eligibility_prob)
    
    # Add value proposition
    md += _generate_value_proposition(eligibility_prob)
    
    # Add provenance
    md += f"""
---

## 📊 PROVENANCE

**Generated By**: Zo (Lead Commander)  
**Pipeline Version**: v2.0 (Modular)  
**Data Source**: AstraDB vector search + Multi-stage filtering  
**Semantic Match Score**: {trial.get('similarity_score', 0):.3f}  
**Composite Score**: {composite_score:.2f} (Stage 1: {stage1.score:.2f}, Stage 2: {stage2.score:.2f}, Stage 3: {stage3.score:.2f}, Stage 4: {stage4.score:.2f})  
**LLM Analysis**: {f"Gemini {GEMINI_MODEL}" if stage5 else "Not performed"}  
**Quality**: ✅ COMMANDER-GRADE INTELLIGENCE (Modular Pipeline v2.0)

---

**RESEARCH USE ONLY (RUO)** - This intelligence report is for research and strategic planning. All enrollment decisions must be reviewed by the patient's oncologist.

---

**⚔️ FOR THE PATIENT!** ⚔️
"""
    
    return md

def _generate_decision_tree(trial, patient, prob):
    """Generate ASCII decision tree"""
    treatment_line = patient.get('treatment', {}).get('line', 'first-line')
    return f"""
## 🚨 CRITICAL DECISION TREE

START: Patient completes {treatment_line} treatment
  │
  ├─→ Biomarker Testing (if required)
  │    │
  │    └─→ **ELIGIBLE FOR TRIAL!** (pending results)
  │         Probability: ~{prob*100:.0f}%
  │
  └─→ END: Enroll in {trial.get('nct_id')}

---
"""

def _generate_strategic_scenarios(trial, patient, prob):
    """Generate strategic scenarios"""
    patient_name = patient.get('demographics', {}).get('name', 'Patient')
    return f"""
## 💡 STRATEGIC IMPLICATIONS

### Best-Case Scenario:
✅ {patient_name} enrolls in {trial.get('nct_id')}
✅ Access to experimental therapy
✅ Close monitoring, expert care
**Probability**: ~{prob*100:.0f}%

### Most Likely Scenario:
Patient completes screening and enrolls successfully (pending biomarkers)

### Challenge Scenario:
Screen failure due to biomarker requirements or other eligibility criteria

---
"""

def _generate_location_section(trial, stage3):
    """Generate location details"""
    md = "## 🏥 LOCATION DETAILS\n\n"
    
    if stage3:
        matching_locs = stage3.metadata.get('matching_locations') or stage3.metadata.get('nyc_locations', [])
        if matching_locs:
            md += "### Matching Locations\n\n"
            for i, loc in enumerate(matching_locs, 1):
                facility = loc.get('facility', 'Unknown')
                city = loc.get('city', 'Unknown')
                state = loc.get('state', 'Unknown')
                md += f"{i}. **{facility}** - {city}, {state}\n"
        else:
            md += "No matching locations found.\n"
    else:
        md += "Location data not available.\n"
    
    md += "\n---\n\n"
    return md

def _generate_critical_gates(trial, patient):
    """Generate critical gates section"""
    md = "## ⚠️ CRITICAL GATES\n\n"
    
    eligibility_lower = trial.get('eligibility_text', '').lower()
    critical_gates = patient.get('critical_gates', {})
    
    if 'her2' in eligibility_lower:
        if 'her2_ihc' in critical_gates:
            gate_info = critical_gates['her2_ihc']
            md += f"""### HER2 Testing (Priority: {gate_info.get('priority', 'P1')})
**Status**: {gate_info.get('status', 'PENDING')}  
**Test**: {gate_info.get('test', 'HER2 IHC')}  
**Turnaround**: {gate_info.get('turnaround', '3-5 days')}  
**Cost**: {gate_info.get('cost', 'TBD')}  
**Rationale**: {gate_info.get('rationale', 'HER2 status may be required for enrollment')}

"""
        else:
            md += "### HER2 Testing\n**Status**: PENDING - HER2 testing may be required for enrollment.\n\n"
    
    if 'hrd' in eligibility_lower or 'homologous recombination' in eligibility_lower:
        if 'hrd_testing' in critical_gates:
            gate_info = critical_gates['hrd_testing']
            md += f"""### HRD Testing (Priority: {gate_info.get('priority', 'P1')})
**Status**: {gate_info.get('status', 'PENDING')}  
**Test**: {gate_info.get('test', 'HRD assay')}  
**Turnaround**: {gate_info.get('turnaround', '7-10 days')}  
**Cost**: {gate_info.get('cost', 'TBD')}  
**Rationale**: {gate_info.get('rationale', 'HRD status may be required for enrollment')}

"""
        else:
            md += "### HRD Testing\n**Status**: PENDING - HRD testing may be required for enrollment.\n\n"
    
    if 'her2' not in eligibility_lower and 'hrd' not in eligibility_lower:
        md += "✅ No critical biomarker gates identified. Proceed with standard eligibility screening.\n"
    
    md += "\n---\n\n"
    return md

def _generate_tactical_recommendations(tier, prob):
    """Generate tactical recommendations"""
    md = "## ⚔️ TACTICAL RECOMMENDATIONS\n\n"
    
    if tier == 'TOP_TIER':
        md += f"""**Priority**: 🔥 **P0 - IMMEDIATE ACTION** (Eligibility: ~{prob*100:.0f}%)

**Next Steps**:
1. **Order biomarker tests** (HER2 IHC, HRD if not done)
2. **Contact trial site** (within 48 hours)
3. **Pre-screen patient** (get on coordinator's radar)
4. **Decision at Week 2**: Enroll if eligible
5. **Prepare medical records** (surgical report, pathology, CA-125 history)

**Expected Timeline**:
- Week 1: Complete L1 chemo (cycle 6)
- Week 2: Biomarker results available
- Week 3: Enroll in trial (if eligible) or proceed with SOC maintenance

"""
    elif tier == 'GOOD_TIER':
        md += f"""**Priority**: ⚠️ **P1 - HIGH PRIORITY** (Eligibility: ~{prob*100:.0f}%)

**Next Steps**:
1. **Review eligibility carefully** (with oncologist)
2. **Order pending biomarker tests** (if required)
3. **Contact trial site** (within 1 week)
4. **Backup option** (if top-tier trials fail)

"""
    else:
        md += f"""**Priority**: 📋 **P2 - CONDITIONAL** (Eligibility: ~{prob*100:.0f}%)

**Next Steps**:
1. **Keep on radar** (monitor for updates)
2. **Consider if other trials fail**
3. **Review eligibility requirements**

"""
    
    md += "\n---\n\n"
    return md

def _generate_value_proposition(prob):
    """Generate value proposition"""
    md = "## 🎯 VALUE PROPOSITION\n\n"
    
    if prob >= 0.25:
        md += f"""**WIN-WIN SCENARIO**:
- If eligible ({prob*100:.0f}% chance) → Access to experimental therapy
- If not eligible → Gets proven SOC (PARP or bevacizumab maintenance)
- Either way, patient receives appropriate care

**Risk-Benefit**: Low risk (pre-screening doesn't commit to enrollment), high reward (cutting-edge therapy)
"""
    else:
        md += f"""**LOW PROBABILITY SCENARIO**:
- Eligibility: ~{prob*100:.0f}% (low)
- Consider alternative trials with better match
- Keep as backup option

**Risk-Benefit**: Consider higher-probability trials first
"""
    
    return md

# Import GEMINI_MODEL for provenance
try:
    from ..stage5_llm_analysis.trial_fit_analyzer import GEMINI_MODEL
except:
    GEMINI_MODEL = "unknown"


