"""
Markdown Assembler - Formats comprehensive analysis as structured markdown.

Takes all generated sections and assembles them into a readable document
matching the structure of AK_CYCLE_2_MOAT_ANALYSIS.md
"""

from typing import Dict, Any, List
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


class MarkdownAssembler:
    """Assemble comprehensive analysis into markdown format."""
    
    def __init__(self):
        pass
    
    def assemble_analysis(
        self,
        sections: Dict[str, Any],
        patient_profile: Dict[str, Any],
        treatment_context: Dict[str, Any]
    ) -> str:
        """
        Assemble complete markdown document.
        
        Args:
            sections: Dict with all analysis sections
            patient_profile: Patient profile data
            treatment_context: Treatment context (drugs, cycle, etc.)
        
        Returns:
            Complete markdown string
        """
        lines = []
        
        # Header
        patient_name = patient_profile.get("demographics", {}).get("name", "Patient")
        treatment_goal = treatment_context.get("treatment_goal", "Treatment Analysis")
        
        lines.append(f"# MOAT COMPREHENSIVE ANALYSIS: {patient_name}")
        lines.append(f"## {treatment_goal}")
        lines.append("")
        lines.append(f"**Generated:** {datetime.now().strftime('%B %Y')}")
        lines.append(f"**Status:** {treatment_context.get('status', 'Active Treatment')}")
        
        current_drugs = treatment_context.get("current_drugs", [])
        if current_drugs:
            drugs_str = " + ".join([d.capitalize() for d in current_drugs])
            lines.append(f"**Treatment:** {drugs_str} {treatment_context.get('treatment_line', 'L1')}")
        
        lines.append("")
        lines.append("---")
        lines.append("")
        
        # How to Read section
        lines.extend(self._assemble_how_to_read())
        lines.append("")
        
        # Patient Summary
        lines.extend(self._assemble_patient_summary(patient_profile, treatment_context))
        lines.append("")
        
        # Critical Genomic Findings
        if sections.get("genomic_findings"):
            lines.extend(self._assemble_genomic_findings(sections["genomic_findings"]))
            lines.append("")
        
        # Key Gene Insight (if critical finding exists)
        critical_findings = sections.get("genomic_findings", {}).get("critical_findings", [])
        if critical_findings:
            # Use the most critical finding
            primary_finding = critical_findings[0]
            lines.extend(self._assemble_key_gene_insight(primary_finding, sections.get("genomic_findings", {})))
            lines.append("")
        
        # Toxicity Assessment
        if sections.get("toxicity_assessment"):
            lines.extend(self._assemble_toxicity_assessment(sections["toxicity_assessment"]))
            lines.append("")
        
        # Nutrition Protocol
        if sections.get("nutrition_protocol"):
            lines.extend(self._assemble_nutrition_protocol(sections["nutrition_protocol"]))
            lines.append("")
        
        # Timing Protocol
        if sections.get("timing_protocol"):
            lines.extend(self._assemble_timing_protocol(sections["timing_protocol"]))
            lines.append("")
        
        # Avoid List
        if sections.get("avoid_list"):
            lines.extend(self._assemble_avoid_list(sections["avoid_list"]))
            lines.append("")
        
        # Treatment Optimization
        if sections.get("treatment_optimization"):
            lines.extend(self._assemble_treatment_optimization(sections["treatment_optimization"]))
            lines.append("")
        
        # MOAT Advantage
        lines.extend(self._assemble_moat_advantage())
        lines.append("")
        
        # Action Items
        if sections.get("action_items"):
            lines.extend(self._assemble_action_items(sections["action_items"]))
            lines.append("")
        
        # Big Picture
        if sections.get("big_picture"):
            lines.extend(self._assemble_big_picture(sections["big_picture"]))
            lines.append("")
        
        # References
        lines.extend(self._assemble_references())
        lines.append("")
        
        # Footer
        lines.append("**MOAT Analysis Generated by AGENT_06_NUTRITION + Integrated MOAT Systems**")
        lines.append("**For Research Use Only - Discuss with Oncology Team**")
        lines.append("")
        
        return "\n".join(lines)
    
    def _assemble_how_to_read(self) -> List[str]:
        """Assemble 'How to Read This Analysis' section."""
        return [
            "## 🎯 HOW TO READ THIS ANALYSIS",
            "",
            "This document connects **YOUR GENOMICS** → **YOUR DRUGS** → **YOUR TOXICITY RISKS** → **YOUR NUTRITION** → **YOUR FUTURE OPTIONS**.",
            "",
            "**The MOAT Approach:**",
            "1. **Genomics First:** Your critical genomic findings affect everything",
            "2. **Drug Mechanism:** How your drugs work (and why they're effective for you)",
            "3. **Pathway Overlap:** Your genomic deficiencies overlap with drug toxicity pathways → specific risks",
            "4. **Targeted Mitigation:** Nutrition recommendations that specifically address YOUR pathway gaps",
            "5. **Future Opportunities:** Genomic findings open doors (PARP inhibitors, immunotherapy) that wouldn't be obvious",
            "",
            "**Key Concepts Throughout:**",
            "- **MoA = Mechanism of Action** (how drugs work)",
            "- **BER = Base Excision Repair** (DNA repair pathway)",
            "- **TMB = Tumor Mutational Burden** (how many mutations your tumor has)",
            "- **Synthetic Lethality =** Exploiting a cancer cell's weakness",
        ]
    
    def _assemble_patient_summary(self, patient_profile: Dict[str, Any], treatment_context: Dict[str, Any]) -> List[str]:
        """Assemble patient summary table."""
        lines = [
            "## 📋 PATIENT SUMMARY",
            "",
            "| Field | Value |",
            "|-------|-------|"
        ]
        
        demographics = patient_profile.get("demographics", {})
        disease = patient_profile.get("disease", {}).get("name", "Unknown")
        
        lines.append(f"| Name | {demographics.get('name', 'Patient')} |")
        lines.append(f"| Diagnosis | {disease} |")
        lines.append(f"| Stage | {patient_profile.get('disease', {}).get('stage', 'Unknown')} |")
        lines.append(f"| Current Treatment | {treatment_context.get('treatment_line', 'L1')} chemotherapy |")
        lines.append(f"| Status | {treatment_context.get('status', 'Active Treatment')} |")
        
        return lines
    
    def _assemble_genomic_findings(self, genomic_data: Dict[str, Any]) -> List[str]:
        """Assemble critical genomic findings section."""
        lines = [
            "## 🧬 CRITICAL GENOMIC FINDINGS",
            ""
        ]
        
        findings = genomic_data.get("critical_findings", [])
        
        for i, finding in enumerate(findings, 1):
            gene = finding.get("gene", "")
            variant = finding.get("variant", "")
            zygosity = finding.get("zygosity", "unknown")
            classification = finding.get("classification", "unknown")
            syndrome = finding.get("syndrome", "")
            
            lines.append(f"### {i}. {gene} {zygosity.upper()} MUTATION" + (" ⚠️ **PATHOGENIC**" if classification == "pathogenic" else ""))
            lines.append(f"- **Variant:** {variant}")
            lines.append(f"- **Zygosity:** {zygosity.upper()}")
            if syndrome:
                lines.append(f"- **Syndrome:** {syndrome}")
            lines.append("")
        
        return lines
    
    def _assemble_key_gene_insight(self, finding: Dict[str, Any], genomic_data: Dict[str, Any]) -> List[str]:
        """Assemble detailed explanation for key gene."""
        gene = finding.get("gene", "")
        biological = genomic_data.get("biological_explanations", {}).get(gene, "")
        clinical = genomic_data.get("clinical_implications", {}).get(gene, "")
        
        # Use LLM-enhanced explanation if available
        llm_explanation = finding.get("llm_enhanced_explanation", "")
        
        lines = [
            f"## 🔬 {gene}: THE CRITICAL INSIGHT",
            "",
            f"### What is {gene}? (The Biology Explained)",
            "",
        ]
        
        # Use LLM explanation if available, otherwise use base
        if llm_explanation:
            lines.append(llm_explanation)
        else:
            lines.append(biological)
        
        lines.append("")
        lines.append("### Clinical Implications of Homozygous Loss (Detailed)")
        lines.append("")
        lines.append("| Implication | Mechanism | Clinical Impact |")
        lines.append("|-------------|-----------|-----------------|")
        
        # Parse clinical implications into table format
        if clinical:
            # Split by "|" if it's already formatted, otherwise create simple row
            if "|" in clinical:
                lines.append(f"| {clinical} |")
            else:
                lines.append(f"| **Key Finding** | {biological[:50]}... | {clinical} |")
        
        return lines
    
    def _assemble_toxicity_assessment(self, toxicity_data: Dict[str, Any]) -> List[str]:
        """Assemble toxicity pathway risk assessment."""
        lines = [
            "## 🧪 TOXICITY PATHWAY RISK ASSESSMENT",
            ""
        ]
        
        drug_explanations = toxicity_data.get("drug_explanations", [])
        
        for drug_data in drug_explanations:
            drug_name = drug_data.get("drug_name", "").upper()
            moa = drug_data.get("moa", "")
            mechanism = drug_data.get("mechanism", "")
            toxicity_risks = drug_data.get("toxicity_risks", [])
            
            lines.append(f"### {drug_name} ({moa.replace('_', ' ').title()}) - Mechanism of Action Explained")
            lines.append("")
            
            # Use LLM-enhanced mechanism if available
            llm_mechanism = drug_data.get("llm_enhanced_mechanism", "")
            if llm_mechanism:
                lines.append("**HOW IT WORKS:**")
                lines.append("")
                lines.append(llm_mechanism)
            else:
                lines.append("**HOW IT WORKS:**")
                for line in mechanism.split("\n"):
                    lines.append(line)
            lines.append("")
            
            if toxicity_risks:
                lines.append("| Toxicity | Risk Level | Patient Impact | Mitigation |")
                lines.append("|----------|------------|---------------|------------|")
                
                for risk in toxicity_risks:
                    lines.append(
                        f"| {risk.get('toxicity', '')} | {risk.get('risk_level', '')} | "
                        f"{risk.get('patient_impact', '')[:50]}... | "
                        f"{risk.get('mitigation', '')[:30]}... |"
                    )
                lines.append("")
        
        return lines
    
    def _assemble_nutrition_protocol(self, nutrition_data: Dict[str, Any]) -> List[str]:
        """Assemble nutrition protocol section."""
        lines = [
            "## 🥗 NUTRITION PROTOCOL FOR CYCLE",
            "",
            "### Supplement Ranking (MOAT-Scored)",
            "",
            "| Supplement | Score | HOW IT WORKS | WHY IT MATTERS FOR YOU |",
            "|------------|-------|--------------|------------------------|"
        ]
        
        supplements = nutrition_data.get("supplements", [])
        for supp in supplements:
            name = supp.get("compound", "")
            score = supp.get("score", 0)
            
            # Use LLM-enhanced explanations if available
            mechanism = supp.get("llm_enhanced_mechanism") or supp.get("mechanism", "")
            rationale = supp.get("llm_enhanced_rationale") or supp.get("rationale", "")
            
            # Truncate for table if needed
            mechanism_display = mechanism[:80] + "..." if len(mechanism) > 80 else mechanism
            rationale_display = rationale[:80] + "..." if len(rationale) > 80 else rationale
            
            lines.append(f"| **{name}** | {score:.2f} | {mechanism_display} | {rationale_display} |")
        
        return lines
    
    def _assemble_timing_protocol(self, timing_data: Dict[str, Any]) -> List[str]:
        """Assemble timing protocol section."""
        lines = [
            "## 📅 CYCLE PREPARATION PROTOCOL",
            ""
        ]
        
        pre_infusion = timing_data.get("pre_infusion", {})
        post_infusion = timing_data.get("post_infusion", {})
        
        if pre_infusion:
            lines.append("### PRE-INFUSION (Days -3 to 0)")
            lines.append("")
            for day, actions in pre_infusion.items():
                lines.append(f"**{day}:**")
                for action in actions:
                    lines.append(f"- ▸ {action}")
                lines.append("")
        
        if post_infusion:
            lines.append("### POST-INFUSION (Days 1-21)")
            lines.append("")
            for phase, actions in post_infusion.items():
                lines.append(f"**{phase}:**")
                for action in actions:
                    lines.append(f"- ▸ {action}")
                lines.append("")
        
        return lines
    
    def _assemble_avoid_list(self, avoid_data: Dict[str, Any]) -> List[str]:
        """Assemble avoid list section."""
        lines = [
            "## 🚫 AVOID LIST (Drug-Food Interactions)",
            "",
            "### ABSOLUTE AVOID"
        ]
        
        absolute_avoid = avoid_data.get("absolute_avoid", [])
        for item in absolute_avoid:
            lines.append(f"- ✗ {item.get('item', '')} ({item.get('reason', '')})")
        
        lines.append("")
        lines.append("### TIMING CRITICAL")
        lines.append("")
        
        timing_critical = avoid_data.get("timing_critical", [])
        for item in timing_critical:
            lines.append(f"- ⏱ {item.get('item', '')}: {item.get('rationale', '')}")
        
        return lines
    
    def _assemble_treatment_optimization(self, optimization_data: Dict[str, Any]) -> List[str]:
        """Assemble treatment optimization section."""
        lines = [
            "## 🎯 TREATMENT OPTIMIZATION RECOMMENDATIONS",
            "",
            "### Testing to Request",
            "",
            "| Test | HOW IT WORKS | WHY YOU NEED IT | Action if Positive |",
            "|------|--------------|-----------------|-------------------|"
        ]
        
        tests = optimization_data.get("tests_to_request", [])
        for test in tests:
            # Use LLM-enhanced explanations if available
            how_explanation = test.get("llm_enhanced_how") or test.get("how", "")
            why_explanation = test.get("llm_enhanced_why") or test.get("why", "")
            
            how_display = how_explanation[:60] + "..." if len(how_explanation) > 60 else how_explanation
            why_display = why_explanation[:60] + "..." if len(why_explanation) > 60 else why_explanation
            
            lines.append(
                f"| **{test.get('name', '')}** | {how_display} | "
                f"{why_display} | {test.get('action', '')[:40]}... |"
            )
        
        return lines
    
    def _assemble_moat_advantage(self) -> List[str]:
        """Assemble MOAT advantage section."""
        return [
            "## 🏆 THE MOAT ADVANTAGE",
            "",
            "### What Generic AI CANNOT Do (and MOAT CAN)",
            "",
            "| Capability | Generic AI | MOAT |",
            "|------------|------------|------|",
            "| Toxicity Prediction | Generic warnings | YOUR genomic profile → specific risks → targeted mitigation |",
            "| Synthetic Lethality | Only BRCA | Your genomic findings → PARP/IO opportunities even if BRCA-negative |",
            "| Timing | Generic advice | Precise timing based on drug half-lives and mechanisms |",
            "| Integration | Siloed advice | Unified: genomics + treatment + toxicity + nutrition + trials |",
        ]
    
    def _assemble_action_items(self, action_items: Dict[str, Any]) -> List[str]:
        """Assemble action items checklist."""
        lines = [
            "## ✅ ACTION ITEMS CHECKLIST",
            ""
        ]
        
        for category, items in action_items.items():
            lines.append(f"### {category.replace('_', ' ').title()}")
            for item in items:
                lines.append(f"- [ ] {item}")
            lines.append("")
        
        return lines
    
    def _assemble_big_picture(self, big_picture: Dict[str, Any]) -> List[str]:
        """Assemble big picture section."""
        lines = [
            "## 🧩 THE BIG PICTURE: HOW EVERYTHING CONNECTS",
            "",
            "### The Chain Reaction Explained",
            ""
        ]
        
        steps = big_picture.get("steps", [])
        for step in steps:
            lines.append(f"**{step.get('title', '')}**")
            lines.append(f"- {step.get('explanation', '')}")
            lines.append("")
        
        lines.append("### The Bottom Line")
        lines.append("")
        lines.append(big_picture.get("bottom_line", "This is personalized precision oncology - not generic advice."))
        
        return lines
    
    def _assemble_references(self) -> List[str]:
        """Assemble references section."""
        return [
            "## 📚 References",
            "",
            "1. Sanders MA et al. \"MBD4 guards against methylation damage and germ line deficiency predisposes to clonal hematopoiesis and early-onset AML.\" Blood. 2018.",
            "2. Palles C et al. \"Germline MBD4 deficiency causes a multi-tumor predisposition syndrome.\" Am J Hum Genet. 2022.",
            "3. Rodrigues DN et al. \"Immunogenomic analyses associate immunological alterations with mismatch repair defects in prostate cancer.\" J Clin Invest. 2018.",
        ]

