"""
Dossier Renderer - Convert dossier dictionary to markdown format.

Generates oncologist-ready markdown dossiers.
"""
from typing import Dict, Any
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

def render_dossier_markdown(dossier: Dict[str, Any]) -> str:
    """
    Render complete 10-section dossier as markdown.
    
    Args:
        dossier: Complete dossier dictionary from dossier_generator
    
    Returns:
        Markdown string
    """
    sections = dossier.get('sections', {})
    nct_id = dossier.get('nct_id', 'UNKNOWN')
    trial_title = dossier.get('trial_title', 'Unknown Trial')
    
    markdown = f"""# ⚔️ CLINICAL TRIAL DOSSIER

**NCT ID**: {nct_id}  
**Trial Title**: {trial_title}  
**Patient ID**: {dossier.get('patient_id', 'unknown')}  
**Generated**: {dossier.get('generated_at', datetime.now().isoformat())}  
**Generated By**: JR2 (Dossier Sidekick)

---

## 1. TRIAL OVERVIEW

**Title**: {sections.get('1_trial_overview', {}).get('title', 'N/A')}  
**Phase**: {sections.get('1_trial_overview', {}).get('phase', 'N/A')}  
**Status**: {sections.get('1_trial_overview', {}).get('status', 'N/A')}  
**Sponsor**: {sections.get('1_trial_overview', {}).get('sponsor', 'N/A')}  
**Estimated Enrollment**: {sections.get('1_trial_overview', {}).get('estimated_enrollment', 'N/A')}  
**Primary Endpoint**: {sections.get('1_trial_overview', {}).get('primary_endpoint', 'N/A')}

**ClinicalTrials.gov**: https://clinicaltrials.gov/study/{nct_id}

---

## 2. ELIGIBILITY ASSESSMENT

**Summary**: {sections.get('2_eligibility_assessment', {}).get('summary', 'N/A')}

### Eligibility Criteria Table

| Criterion | Status | Confidence | Notes |
|-----------|--------|------------|-------|
"""
    
    # Add eligibility table rows
    for criterion in sections.get('2_eligibility_assessment', {}).get('table', []):
        status_emoji = {
            'PASS': '✅',
            'FAIL': '❌',
            'PENDING': '⚠️',
            'REVIEW': '📋'
        }.get(criterion.get('status', ''), '❓')
        
        markdown += f"| {criterion.get('criterion', 'N/A')} | {status_emoji} {criterion.get('status', 'N/A')} | {criterion.get('confidence', 0.0):.2f} | {criterion.get('notes', 'N/A')} |\n"
        
        # Add pending tests if any
        if criterion.get('pending_tests'):
            markdown += f"|   → Pending Tests | | | {', '.join(criterion['pending_tests'])} |\n"
    
    markdown += "\n---\n\n## 3. STRATEGIC SCENARIOS\n\n"
    
    # Add scenarios
    scenarios = sections.get('3_strategic_scenarios', {})
    for scenario_name, scenario_data in scenarios.items():
        scenario_title = scenario_name.replace('_', ' ').title()
        markdown += f"### {scenario_title}\n\n"
        markdown += f"**Eligibility Probability**: {scenario_data.get('probability', 0.0):.1%}\n\n"
        markdown += f"**Scenario**: {scenario_data.get('scenario', 'N/A')}\n\n"
        markdown += f"**Eligibility Level**: {scenario_data.get('eligibility', 'N/A')}\n\n"
    
    markdown += "---\n\n## 4. TACTICAL RECOMMENDATIONS\n\n"
    
    # Add recommendations
    recommendations = sections.get('4_tactical_recommendations', [])
    if recommendations:
        markdown += "| Action | Lab | Cost | Timeline | Priority | Rationale |\n"
        markdown += "|--------|-----|------|----------|----------|----------|\n"
        for rec in recommendations:
            markdown += f"| {rec.get('action', 'N/A')} | {rec.get('lab', 'N/A')} | {rec.get('cost', 'N/A')} | {rec.get('timeline', 'N/A')} | {rec.get('priority', 'N/A')} | {rec.get('rationale', 'N/A')} |\n"
    else:
        markdown += "No pending actions required.\n"
    
    markdown += "\n---\n\n## 5. DRUG MECHANISMS\n\n"
    
    # Add drug mechanisms
    drug_mechanisms = sections.get('5_drug_mechanisms', {})
    for drug_name, mechanism in drug_mechanisms.items():
        markdown += f"### {drug_name}\n\n"
        markdown += f"**Mechanism (Technical)**: {mechanism.get('mechanism', 'N/A')}\n\n"
        markdown += f"**Mechanism (Layman)**: {mechanism.get('layman', 'N/A')}\n\n"
        markdown += f"**Evidence Tier**: {mechanism.get('evidence_tier', 'N/A')}\n\n"
    
    # Add efficacy analysis section (Task 2.1)
    efficacy_analysis = sections.get('6_drug_efficacy_analysis', {})
    if efficacy_analysis and efficacy_analysis.get('status') != 'not_available':
        markdown += "\n---\n\n## 6. DRUG EFFICACY ANALYSIS (S/P/E)\n\n"
        markdown += "**Evidence Tier**: {}\n\n".format(efficacy_analysis.get('evidence_tier', 'N/A'))
        markdown += "**Scoring Strategy**: {}\n\n".format(efficacy_analysis.get('scoring_strategy', {}).get('mode', 'N/A'))
        
        top_drugs = efficacy_analysis.get('top_drugs', [])
        if top_drugs:
            markdown += "### Top Recommended Drugs\n\n"
            markdown += "| Rank | Drug | Efficacy Score | Confidence | Evidence Tier | Badges |\n"
            markdown += "|------|------|----------------|------------|---------------|--------|\n"
            for i, drug in enumerate(top_drugs, 1):
                badges = ', '.join(drug.get('badges', [])) or 'None'
                markdown += f"| {i} | {drug.get('name', 'N/A')} | {drug.get('efficacy_score', 0.0):.3f} | {drug.get('confidence', 0.0):.3f} | {drug.get('evidence_tier', 'N/A')} | {badges} |\n"
            
            markdown += "\n### Rationale\n\n"
            for drug in top_drugs[:3]:  # Top 3 drugs
                rationale = drug.get('rationale', [])
                if rationale:
                    markdown += f"**{drug.get('name', 'N/A')}**:\n"
                    for r in rationale[:2]:  # Top 2 rationale points
                        markdown += f"- {r}\n"
                    markdown += "\n"
    else:
        markdown += "\n---\n\n## 6. DRUG EFFICACY ANALYSIS\n\n"
        markdown += "*Efficacy analysis not available. {}\n\n".format(efficacy_analysis.get('reason', 'No mutations provided') if efficacy_analysis else 'No mutations provided')
    
    markdown += "\n---\n\n## 7. LOCATION DETAILS\n\n"
    
    # Add locations
    locations = sections.get('6_location_details', [])
    if locations:
        markdown += "| Facility | City | State | Country |\n"
        markdown += "|----------|------|-------|----------|\n"
        for loc in locations:
            markdown += f"| {loc.get('facility', 'N/A')} | {loc.get('city', 'N/A')} | {loc.get('state', 'N/A')} | {loc.get('country', 'N/A')} |\n"
    else:
        markdown += "No location data available.\n"
    
    markdown += "\n---\n\n## 8. TIMELINE\n\n"
    
    timeline = sections.get('8_timeline', {})
    markdown += f"**Study Start Date**: {timeline.get('study_start', 'N/A')}\n\n"
    markdown += f"**Primary Completion Date**: {timeline.get('primary_completion', 'N/A')}\n\n"
    
    markdown += "---\n\n## 9. FULL ELIGIBILITY TEXT\n\n"
    
    eligibility_text = sections.get('9_full_eligibility_text', {})
    markdown += "### Inclusion Criteria\n\n"
    inclusion = eligibility_text.get('inclusion_criteria', '') or eligibility_text.get('inclusion', 'N/A')
    markdown += f"{inclusion if inclusion else 'Not available'}\n\n"
    markdown += "### Exclusion Criteria\n\n"
    exclusion = eligibility_text.get('exclusion_criteria', '') or eligibility_text.get('exclusion', 'N/A')
    markdown += f"{exclusion if exclusion else 'Not available'}\n\n"
    
    markdown += "---\n\n## 10. CONTACT INFORMATION\n\n"
    
    contacts = sections.get('10_contact_information', [])
    if contacts:
        for i, contact in enumerate(contacts, 1):
            markdown += f"### Site {i}\n\n"
            markdown += f"**Facility**: {contact.get('facility', 'N/A')}\n\n"
            markdown += f"**Location**: {contact.get('city', 'N/A')}, {contact.get('state', 'N/A')}\n\n"
            if contact.get('contact'):
                markdown += f"**Contact**: {contact.get('contact', 'N/A')}\n\n"
    else:
        markdown += "Contact information not available.\n\n"
    
    markdown += "---\n\n## 11. PROVENANCE\n\n"
    
    provenance = sections.get('11_provenance', {})
    markdown += f"**Generated By**: {provenance.get('generated_by', 'N/A')}\n\n"
    markdown += f"**Data Sources**: {', '.join(provenance.get('data_sources', []))}\n\n"
    markdown += f"**Confidence Flags**: {', '.join(provenance.get('confidence_flags', []))}\n\n"
    
    markdown += "---\n\n**RESEARCH USE ONLY (RUO)** - This dossier is for research purposes only and should not be used for clinical decision-making without proper medical review.\n\n"
    
    logger.info(f"✅ Rendered markdown dossier for {nct_id}")
    return markdown

